# cp examples/example-settings-api.yml settings-api.yml

Name: gmp-tickets-example
Host: 0.0.0.0
Port: "12300"
Read_timeout: 5s
Read_header_timeout: 5s
Write_timeout: 10s
Idle_timeout: 2m0s
Log_to_console: true
Log_to_file: false
Log_to_storage: false

