version: '3'


#  docker-compose down --volumes

services:

  postgres-tickets:
    image: postgres:latest
    volumes:
      - ./build/tickets/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: gmp-postgres-tickets
    env_file:
      - build/tickets/docker/dev.tickets.database.env
    ports:
      - "5432:5432/tcp"

  postgres-persons:
    image: postgres:latest
    volumes:
      - ./build/users/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: gmp-postgres-persons
    env_file:
      - build/users/docker/dev.users.database.env
    ports:
      - "5532:5432/tcp"
